### ISSUE TITLE
server.all and non-mandatory param

### ISSUE THREAD

**Issue by diorahman** [kilianc/node-apiserver#18]
Can we define an endpoint to handle all verbs? and define non-mandatory params as in Express?

for example:

``` javascript
server.all('/svc/:id/:connectionType?', function(req, res){

})
```

Where all means we will handle all verbs while `?` defines non-mandatory param of  `connectionType`

Thanks!

**Comment by kilianc** [comment]
to define a catchall simply don't use an object as endpoint:

``` js
apiServer.addModule('1', 'fooModule', {
  foo: function (request, response) {
    // all http verbs
  }
})
```

in apiserver all parameters are optional

`'/svc/:id/:connectionType'` matches

```
/svc/50/tcp
/svc/50/
/svc/50
/svc/
/svc
```

**Comment by diorahman** [comment]
Thanks

**Comment by kilianc** [comment]
you're welcome! :punch:
