### ISSUE TITLE
request body buffer not initiating on POST requests

### ISSUE THREAD

**Issue by skliffmueller** [kilianc/node-apiserver#24]
This was an issue I experiences with both the example script and my own scripts.
When trying to parse the body buffer on a post request, the event listeners for .on('data' and .once('end' would not trigger.
I came up with a fix by wiping out lines 6 and 104 on apiserver.js disabling buffered-request module as node http now handles these events by default.

You may see my fork at https://github.com/skliffmueller/node-apiserver

**Comment by kilianc** [comment]
@skliffmueller response stream is paused by default as it will be in 0.11. you need to call `res.resume()`

**Comment by kilianc** [comment]
If you look at the docs

> Payload paused by default

**Comment by skliffmueller** [comment]
res.resume is in my scripting, and I've experienced that buffered-request breaks the event listener. Try your example and a fresh install of your node_modules.

Under the Quick look, I've taken the exact script and did a fresh npm install of apiserver. I experience the same issue with that as my own script.

It's not a major issue with the script, it's just that it's 2 years old and node http handles things a little differently now and no longer requires buffered-request module as node http does it by default.

**Comment by kilianc** [comment]
@skliffmueller after further investigation I can confirm that you're right. I just released v0.3 with should close this.

Please let me know!

**Comment by skliffmueller** [comment]
Testing and confirmed working! Thanks a lot for your quick response. Happy development.

**Comment by skliffmueller** [comment]
Hey quick note to get Travis CI to give you a successful test, bump your package.json node version to >=0.8.0 as formidable has updated.

**Comment by kilianc** [comment]
I know I know, I got the alerts last night :) If I am not too lazy today will do :)
